code/objects/ApplicationSettings__c.object
<CustomObject>
    <fields>
        <fullName>Active_Form_Instance_Status__c</fullName>
        <label>Active Form Instance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>AttachmentTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Complete_Form_Instance_Status__c</fullName>
        <label>Complete Form Instance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactMergeFields__c</fullName>
        <label>Contact Merge Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ContactTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>ContactTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Anonymous_Leads__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Anonymous Leads</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Debug__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Debug</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DefaultGateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Gateway</label>
        <referenceTo>Gateway__c</referenceTo>
        <relationshipLabel>Application Settings</relationshipLabel>
        <relationshipName>Application_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FormTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>FormTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeadMergeFields__c</fullName>
        <label>Lead Merge Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LeadTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>LeadTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PossibleAnswerDelimiter__c</fullName>
        <label>Possible Answer Delimiter</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMSTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>SMSTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Setting</label>
    <nameField>
        <label>Application Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mogli_Number__c</fullName>
        <description>This is the gateway formatted phone number</description>
        <externalId>true</externalId>
        <inlineHelpText>This is the gateway formatted phone number</inlineHelpText>
        <label>Mogli Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

code/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FormTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Form Template</label>
        <referenceTo>FormTemplate__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form</label>
    <nameField>
        <displayFormat>FN{0000000000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/FormTemplate__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form Template</label>
    <nameField>
        <label>Form Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/Gateway__c.object
<CustomObject>
    <fields>
        <fullName>PhoneNumber__c</fullName>
        <label>Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TwilioAccountSid__c</fullName>
        <label>Twilio AccountSid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TwilioAuthToken__c</fullName>
        <label>Twilio AuthToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WebHookIdentifier__c</fullName>
        <label>WebHook Identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Gateway</label>
    <nameField>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <recordTypes>
        <fullName>Twilio</fullName>
        <active>true</active>
        <description>Twilio Gateway</description>
        <label>Twilio</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Mogli_Number__c</fullName>
        <externalId>true</externalId>
        <label>Mogli Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

code/objects/PossibleAnswer__c.object
<CustomObject>
    <fields>
        <fullName>PossibleText__c</fullName>
        <label>Possible Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>QuestionTemplate__c</fullName>
        <label>Question Template</label>
        <referenceTo>QuestionTemplate__c</referenceTo>
        <relationshipLabel>Possible Answers</relationshipLabel>
        <relationshipName>Possible_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Possible Answer</label>
    <nameField>
        <displayFormat>PAN{0000000000}</displayFormat>
        <label>Possible Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Possible Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

code/objects/QuestionTemplate__c.object
<CustomObject>
    <fields>
        <fullName>FirstQuestion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Question</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FormTemplate__c</fullName>
        <label>Form Template</label>
        <referenceTo>FormTemplate__c</referenceTo>
        <relationshipLabel>Question Templates</relationshipLabel>
        <relationshipName>Question_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Message_Text__c</fullName>
        <label>Message Text</label>
        <type>TextArea</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

code/objects/SMS_Template__c.object
<CustomObject>
    <fields>
        <fullName>FormTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The form that will be initiated upon sending this template</description>
        <inlineHelpText>The form that will be initiated upon sending this template</inlineHelpText>
        <label>Form Template</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Active Forms maybe selected</errorMessage>
            <filterItems>
                <field>FormTemplate__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <infoMessage>Only Active Forms maybe selected</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FormTemplate__c</referenceTo>
        <relationshipLabel>SMS Templates</relationshipLabel>
        <relationshipName>SMS_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <label>SMS Template</label>
    <nameField>
        <displayFormat>ST{YY}{MM}{DD}-{0000000000}</displayFormat>
        <label>SMS Template #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/classes/TestUtil.cls
@isTest
public class TestUtil
{
    public static final Integer TEST_THROTTLE = 10;
    /**************************************************************************
     * setStandardTestConditions
     **************************************************************************/
    public static void setStandardTestConditions() {

        
        //Gateway__c gtw = new Gateway__c(PhoneNumber__c = '123456789',
        //                                TwilioAccountSid__c = '12345',
        //                                TwilioAuthToken__c = '12345',
        //                                WebHookIdentifier__c = '1',
        //                                RecordTypeID = MogliUtil.getRecordTypeIdByLabelName('Gateway__c', 'Twilio'));
        //insert gtw;

        //ApplicationSettings__c app = new ApplicationSettings__c(Active_Form_Instance_Status__c = 'Active',
        //                                                          AttachmentTrigger__c = true,
        //                                                          Complete_Form_Instance_Status__c = 'Complete',
        //                                                          ContactMergeFields__c = 'Name, Title, LeadSource',
        //                                                          ContactTrigger__c = true,
        //                                                          Create_Anonymous_Leads__c = true,
        //                                                          Debug__c = true,
        //                                                          DefaultGateway__c = gtw.id,
        //                                                          FormTrigger__c = true,
        //                                                          LeadMergeFields__c = 'Name, Title, LeadSource',
        //                                                          LeadTrigger__c = true,
        //                                                          PossibleAnswerDelimiter__c = ':::',
        //                                                          SMSTrigger__c = true,
        //                                                          Name = 'Default');
        //insert app;
        System.debug('appSettings:'+MogliSMSSettings.getAppSettings());
        system.assert(true);
            
    }


    /**************************************************************************
     * createAndInsertLeads
     **************************************************************************/
    public static Map<ID, Lead> createAndInsertLeads(Integer cnt) {
      system.assert(true);
        List<Lead> lds = new List<Lead>();
        for (Integer i = 0; i<cnt; i++){
            lds.add(new Lead(LastName = 'Test Lead '+String.valueOf(cnt),
                              Company = 'Test Company '+String.valueOf(cnt),
                              MobilePhone = '555555555'+String.valueOf(cnt),
                              Mogli_Number__c = '555555555'+String.valueOf(cnt)));
        }
        insert lds;
        Map<ID, Lead> ldMap = new Map<ID, Lead>([SELECT id, LastName, MobilePhone, Mogli_Number__c from Lead]);
        return ldMap;
    }

    /**************************************************************************
     * createAndInsertContacts
     **************************************************************************/
    public static Map<ID, Contact> createAndInsertContacts(Integer cnt) {
      system.assert(true);
        List<Contact> conts = new List<Contact>();
        for (Integer i = 0; i<cnt; i++){
            conts.add(new Contact(LastName = 'Test Contact '+String.valueOf(i),
                                     MobilePhone = '555555555'+String.valueOf(i),
                                     Mogli_Number__c = '555555555'+String.valueOf(i)));
        }
        insert conts;
        Map<ID, Contact> contMap = new Map<ID, Contact>([SELECT id, LastName, MobilePhone, Mogli_Number__c from Contact]);
        return contMap;
    }

    /**************************************************************************
     * createAndInsertFormTemplates
     **************************************************************************/
    public static Map<ID, FormTemplate__c> createAndInsertFormTemplates(Integer cnt) {
      system.assert(true);
        List<FormTemplate__c> formTs = new List<FormTemplate__c>();
        for (Integer i = 0; i<cnt; i++){
            formTs.add(new FormTemplate__c(Name = 'Test Form Template '+String.valueOf(cnt)));
        }
        insert formTs;
        Map<ID, FormTemplate__c> formTemplateMap = new Map<ID, FormTemplate__c>([SELECT id, Name, Status__c from FormTemplate__c]);
        return formTemplateMap;
    }

    /**************************************************************************
     * updateFormTemplatesToActive
     **************************************************************************/
    public static Map<ID, FormTemplate__c> updateFormTemplatesToActive(List<FormTemplate__c> formTemplates) {
      system.assert(true);
        for (FormTemplate__c formTemplate : formTemplates){
            formTemplate.Status__c = 'Active';
        }
        update formTemplates;
        Map<ID, FormTemplate__c> formTemplateMap = new Map<ID, FormTemplate__c>([SELECT id, Name, Status__c from FormTemplate__c]);
        return formTemplateMap;
    }


    /**************************************************************************
     * createAndInsertQuestionTemplates
     **************************************************************************/
    public static Map<ID, QuestionTemplate__c> createAndInsertQuestionTemplates(Integer cnt, List<FormTemplate__c> formTemplates) {
      system.assert(true);
        List<QuestionTemplate__c> questionTs = new List<QuestionTemplate__c>();
        for (FormTemplate__c formT : formTemplates){
            for (Integer i = 0; i<cnt; i++){
                QuestionTemplate__c questionT = new QuestionTemplate__c(Name = formT.Name + ' Test Question Template '+String.valueOf(cnt),
                                                       FormTemplate__c = formT.id,
                                                       Message_Text__c = formT.name + ' Test Question Template Text '+String.valueOf(cnt));
                if(i == 0){
                    questionT.FirstQuestion__c = true;
                } else {
                    questionT.FirstQuestion__c = false;
                }
                questionTs.add(questionT);
            }           
        }
        insert questionTs;
        Map<ID, QuestionTemplate__c> questionTemplateMap = new Map<ID, QuestionTemplate__c>([SELECT id, Name, FormTemplate__c, Message_Text__c from QuestionTemplate__c]);
        return questionTemplateMap;
    }
    /**************************************************************************
     * createAndInsertPossibleAnswers
     **************************************************************************/
    public static Map<ID, PossibleAnswer__c> createAndInsertPossibleAnswers(Integer cnt, List<QuestionTemplate__c> questions) {
      system.assert(true);
        List<PossibleAnswer__c> answers = new List<PossibleAnswer__c>();
        for (QuestionTemplate__c question : questions){
            for (Integer i = 0; i<cnt; i++){
                answers.add(new PossibleAnswer__c(PossibleText__c = question.Name + 'Possible Answer '+String.valueOf(cnt),
                                                       QuestionTemplate__c = question.id));
            }           
        }
        insert answers;
        Map<ID, PossibleAnswer__c> answersMap = new Map<ID, PossibleAnswer__c>([SELECT id, PossibleText__c, QuestionTemplate__c from PossibleAnswer__c]);
        return answersMap;
    }
    /**************************************************************************
     * createAndInsertSMSTemplates
     **************************************************************************/
    public static Map<ID, SMS_Template__c> createAndInsertSMSTemplates(Integer cnt, List<FormTemplate__c> formTemplates) {
      system.assert(true);
        List<SMS_Template__c> templates = new List<SMS_Template__c>();
        for (Integer i = 0; i<cnt; i++){
            templates.add(new SMS_Template__c(Name__c = 'Template '+i,
                                                      Text__c = 'whatever',
                                                      FormTemplate__c = formTemplates[i].id));
        }
        insert templates;
        Map<ID, SMS_Template__c> templatesByID = new Map<ID, SMS_Template__c>([SELECT id, Text__c, Name__c from SMS_Template__c]);
        return templatesByID;
    }
    
    /**************************************************************************
     * createAndInsertFormsForContacts
     **************************************************************************/
    public static Map<ID, Form__c> createAndInsertFormsForContacts(Integer cnt, List<Contact> contacts, String status) {
      system.assert(true);
        List<Form__c> forms = new List<Form__c>();
		Map<ID, Contact> contMap = new Map<ID,Contact>([Select id, Mogli_Number__c, MobilePhone from Contact]);
        for(Contact cont : contacts){
            for (Integer i = 0; i<cnt; i++){			
                forms.add(new Form__c(Contact__c = cont.id,
//                                      Phone_Number__c = contMap.get(cont.id).MobilePhone,
                                      Phone_Number__c = contMap.get(cont.id).Mogli_Number__c,
                                      Status__c = status));
            }            
        }
        insert forms;
        Map<ID, Form__c> formsByID = new Map<ID, Form__c>([SELECT id, Contact__c, Status__c, FormTemplate__c from Form__c]);
        return formsByID;
    }

    @isTest
    public static void getCoverage(){
      MogliUtil.testCoverage();
    }
}