code/objects/ApplicationSettings__c.object
<CustomObject>
    <fields>
        <fullName>Active_Form_Instance_Status__c</fullName>
        <label>Active Form Instance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>AttachmentTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Complete_Form_Instance_Status__c</fullName>
        <label>Complete Form Instance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactMergeFields__c</fullName>
        <label>Contact Merge Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ContactTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>ContactTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Anonymous_Leads__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Anonymous Leads</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Debug__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Debug</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DefaultGateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Gateway</label>
        <referenceTo>Gateway__c</referenceTo>
        <relationshipLabel>Application Settings</relationshipLabel>
        <relationshipName>Application_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FormTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>FormTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeadMergeFields__c</fullName>
        <label>Lead Merge Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LeadTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>LeadTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PossibleAnswerDelimiter__c</fullName>
        <label>Possible Answer Delimiter</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMSTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>SMSTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Setting</label>
    <nameField>
        <label>Application Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/Gateway__c.object
<CustomObject>
    <fields>
        <fullName>CustomSMSServiceHandler__c</fullName>
        <label>Custom SMSServiceHandler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomWebServiceHandler__c</fullName>
        <label>Custom WebServiceHandler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PhoneNumber__c</fullName>
        <label>Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TwilioAccountSid__c</fullName>
        <label>Twilio AccountSid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TwilioAuthToken__c</fullName>
        <label>Twilio AuthToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WebHookIdentifier__c</fullName>
        <label>WebHook Identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Gateway</label>
    <nameField>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <recordTypes>
        <fullName>Twilio</fullName>
        <active>true</active>
        <description>Twilio Gateway</description>
        <label>Twilio</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/MogliSMS_Settings__mdt.object
<CustomObject>
    <fields>
        <fullName>Active_Form_Instance_Status__c</fullName>
        <label>Active Form Instance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>AttachmentTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Complete_Form_Instance_Status__c</fullName>
        <defaultValue>&quot;Complete&quot;</defaultValue>
        <description>This is the status the Form__c records will be updated to when a new form is created with the value in the &quot;Active&quot; Status</description>
        <inlineHelpText>This is the status the Form__c records will be updated to when a new form is created with the value in the &quot;Active&quot; Status</inlineHelpText>
        <label>Complete Form Instance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactMergeFields__c</fullName>
        <description>Enter additional fields that maybe used for Contact field merge on the SMS object</description>
        <inlineHelpText>Enter additional fields that maybe used for Contact field merge on the SMS object</inlineHelpText>
        <label>Contact Merge Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ContactTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this field is checked the ContactTrigger will fire</description>
        <inlineHelpText>If this field is checked the ContactTrigger will fire</inlineHelpText>
        <label>ContactTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Anonymous_Leads__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Anonymous Leads</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CustomSMSServiceHandler__c</fullName>
        <label>CustomSMSServiceHandler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomWebServiceHandler__c</fullName>
        <label>CustomWebServiceHandler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Debug__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Debug</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FormTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this field is checked the FormTrigger will fire</description>
        <inlineHelpText>If this field is checked the FormTrigger will fire</inlineHelpText>
        <label>FormTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gateway__c</fullName>
        <defaultValue>&quot;TWILIO&quot;</defaultValue>
        <label>Gateway</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadMergeFields__c</fullName>
        <description>Enter additional fields that maybe used for Lead field merge on the SMS object</description>
        <inlineHelpText>Enter additional fields that maybe used for Lead field merge on the SMS object</inlineHelpText>
        <label>Lead Merge Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LeadTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this field is checked, the lead trigger will fire</description>
        <inlineHelpText>If this field is checked, the lead trigger will fire</inlineHelpText>
        <label>LeadTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PossibleAnswerDelimiter__c</fullName>
        <defaultValue>&quot;:::&quot;</defaultValue>
        <description>This is the string delimiter that should be at the end of each possible answer in the PossibleAnswer__c.PossibleText__c field.</description>
        <inlineHelpText>This is the string delimiter that should be at the end of each possible answer in the PossibleAnswer__c.PossibleText__c field.</inlineHelpText>
        <label>Possible Answer Delimiter</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMSTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this field is checked the SMSTrigger will fire</description>
        <inlineHelpText>If this field is checked the SMSTrigger will fire</inlineHelpText>
        <label>SMSTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TelerivetAPIKey__c</fullName>
        <label>TelerivetAPIKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TelerivetPhoneId__c</fullName>
        <label>TelerivetPhoneId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TelerivetProjectID__c</fullName>
        <label>TelerivetProjectID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TelerivetSecret__c</fullName>
        <label>TelerivetSecret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TwilioAccountSid__c</fullName>
        <label>TwilioAccountSid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TwilioAuthToken__c</fullName>
        <label>TwilioAuthToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TwilioPhone__c</fullName>
        <label>TwilioPhone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MogliSMS Settings</label>
    <pluralLabel>MogliSMS Settings</pluralLabel>
</CustomObject>

code/classes/MogliSMSSettings.cls
global with sharing class MogliSMSSettings {
    global static MogliSMS_Settings__mdt settings = [SELECT Id, DeveloperName, MasterLabel, Gateway__c, Language, NamespacePrefix,
                                        Label, QualifiedApiName, CustomWebServiceHandler__c, TwilioAccountSid__c, TwilioAuthToken__c,
                                        TelerivetProjectID__c, TelerivetSecret__c, TwilioPhone__c, CustomSMSServiceHandler__c,
                                        TelerivetPhoneId__c, TelerivetAPIKey__c,ContactTrigger__c, SMSTrigger__c,
                                        Active_Form_Instance_Status__c, Complete_Form_Instance_Status__c, FormTrigger__c,
                                        PossibleAnswerDelimiter__c, Create_Anonymous_Leads__c, AttachmentTrigger__c,
                                        LeadMergeFields__c, ContactMergeFields__c, Debug__c,
                                        LeadTrigger__c 
                                        FROM MogliSMS_Settings__mdt WHERE DeveloperName = 'MogliSMSSettings' limit 1];

//add these back in once the bug is fixed https://success.salesforce.com/issues_view?id=a1p300000008bS6AAI
                                        //QuestionResponseTrigger__c,
                                        //SMSTemplateTrigger__c,
    global static ApplicationSettings__c appSettings;

    public static ApplicationSettings__c getAppSettings(){
        try{
            if(appSettings == null){
                appSettings = [SELECT Id, ContactTrigger__c, SMSTrigger__c,
                                        Active_Form_Instance_Status__c, Complete_Form_Instance_Status__c, FormTrigger__c,
                                        PossibleAnswerDelimiter__c, Create_Anonymous_Leads__c, AttachmentTrigger__c,
                                        LeadMergeFields__c, ContactMergeFields__c, Debug__c, DefaultGateway__c,
                                        LeadTrigger__c
                                        FROM ApplicationSettings__c WHERE Name = 'Default' limit 1];
            }   
        } catch (Exception e) {

            Gateway__c gtw = new Gateway__c(PhoneNumber__c = '123456789',
                                            TwilioAccountSid__c = '12345',
                                            TwilioAuthToken__c = '12345',
                                            WebHookIdentifier__c = '1',
                                            RecordTypeID = MogliUtil.getRecordTypeIdByLabelName('Gateway__c', 'Twilio'));
            insert gtw;

            appSettings = new ApplicationSettings__c(Active_Form_Instance_Status__c = 'Active',
                                                                  AttachmentTrigger__c = true,
                                                                  Complete_Form_Instance_Status__c = 'Complete',
                                                                  ContactMergeFields__c = 'Name, Title, LeadSource',
                                                                  ContactTrigger__c = true,
                                                                  Create_Anonymous_Leads__c = true,
                                                                  Debug__c = true,
                                                                  DefaultGateway__c = gtw.id,
                                                                  FormTrigger__c = true,
                                                                  LeadMergeFields__c = 'Name, Title, LeadSource',
                                                                  LeadTrigger__c = true,
                                                                  PossibleAnswerDelimiter__c = ':::',
                                                                  SMSTrigger__c = true,
                                                                  Name = 'Default');


            insert appSettings;

        }
        return appSettings;
    }
}