code/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mogli_Number__c</fullName>
        <description>This is the gateway formatted phone number</description>
        <externalId>true</externalId>
        <inlineHelpText>This is the gateway formatted phone number</inlineHelpText>
        <label>Mogli Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

code/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form</label>
    <nameField>
        <displayFormat>FN{0000000000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/Gateway__c.object
<CustomObject>
    <fields>
        <fullName>CustomSMSServiceHandler__c</fullName>
        <label>Custom SMSServiceHandler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TwilioAccountSid__c</fullName>
        <label>Twilio AccountSid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TwilioAuthToken__c</fullName>
        <label>Twilio AuthToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Gateway</label>
    <nameField>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <recordTypes>
        <fullName>Custom</fullName>
        <active>true</active>
        <description>Custom Gateway</description>
        <label>Custom</label>
    </recordTypes>
    <recordTypes>
        <fullName>Twilio</fullName>
        <active>true</active>
        <description>Twilio Gateway</description>
        <label>Twilio</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Mogli_Number__c</fullName>
        <externalId>true</externalId>
        <label>Mogli Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

code/objects/SMS__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SMS</relationshipLabel>
        <relationshipName>SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gateway</label>
        <referenceTo>Gateway__c</referenceTo>
        <relationshipLabel>SMS</relationshipLabel>
        <relationshipName>SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>SMS</relationshipLabel>
        <relationshipName>SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Scheduled_Delivery__c</fullName>
        <label>Scheduled Delivery</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Sending</fullName>
                </value>
                <value>
                    <fullName>Sent Successfully</fullName>
                </value>
                <value>
                    <fullName>Received Successfully</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS{YY}{MM}{DD}-{0000}</displayFormat>
        <label>SMS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/classes/MogliSMSService.cls
global with sharing class MogliSMSService {
    global interface IMogliSMSServiceHandler {
        MogliSendSMSOutput sendSMSMessage (MogliSendSMSInput input);
    }
    global class MogliSendSMSInput {
        global String phoneNumber {get;set;}
        global String smsBody {get;set;}
        global String originationID {get;set;}
        global MogliSendSMSInput(String phoneNumber, String smsBody){
            this.phoneNumber = phoneNumber;
            this.smsBody = smsBody;
        }
    }
    global class MogliSendSMSOutput {
        global MogliSendSMSOutput(){

        }        
    }

    global class TwilioSendSMSHandler implements IMogliSMSServiceHandler{
        public MogliSendSMSOutput sendSMSMessage (MogliSendSMSInput input){
System.debug('MogliSMSService.TwilioSendSMSHandler()');
          



            if(!Test.isRunningTest()){
                TwilioRestClient client = new TwilioRestClient(MogliSMSSettings.settings.TwilioAccountSid__c,
                    MogliSMSSettings.settings.TwilioAuthToken__c);

                Map<String,String> properties = new Map<String,String> {
                    'To'   => input.phoneNumber,
                    'From' =>  MogliSMSSettings.settings.TwilioPhone__c,
                    'Body' => input.smsBody
                };
                TwilioMessage message = client.getAccount().getMessages().create(properties);
                System.debug('message:'+message);
            }



            return new MogliSendSMSOutput();
        
       }
    }

    global class TelerivetSendSMSHandler implements IMogliSMSServiceHandler{
        public MogliSendSMSOutput sendSMSMessage(MogliSendSMSInput input){
            //moving out of package
/*System.debug('MogliSMSService.TelerivetSendSMSHandler()');

  
            HTTPRequest req = new HTTPRequest();

            String encodedPhoneID = EncodingUtil.urlEncode(MogliSMSSettings.settings.TelerivetPhoneID__c,'UTF-8');
            String encodedPhoneNumber = EncodingUtil.urlEncode(input.phoneNumber,'UTF-8');
            String encodedMsg        = EncodingUtil.urlEncode(input.smsBody,'UTF-8');

            String reqUrl = 'https://api.telerivet.com/v1/projects/'+MogliSMSSettings.settings.TelerivetProjectID__c+'/messages/outgoing?';
            reqUrl = reqUrl + 'phone_id='+encodedPhoneID+'&to_number='+encodedPhoneNumber+'&content='+encodedMsg;
            
            req.setEndPoint(reqURL);

            Blob headerValue = Blob.valueOf(MogliSMSSettings.settings.TelerivetAPIKey__c+':'+'');
            String authorizationHeader = 'Basic '+ EncodingUtil.base64Encode(headerValue);
            req.setHeader('Authorization', authorizationHeader);
            req.setHeader('Content-Type', 'application/json');
            req.setHeader('Accept', 'application/json');
            req.setTimeout(20000);
            req.setMethod('POST');

            system.debug('req:'+req);
            
            HTTPResponse res = new HTTPResponse();
            if(!Test.isRunningTest()){
                res = new Http().send(req);                
            }


            system.debug('res:'+res);
            system.debug('res.getBody():'+res.getBody());
            system.debug('res.getStatus()'+res.getStatus());
            system.debug('res.getStatusCode():'+res.getStatusCode());

            JSONParser parser = JSON.createParser(res.getBody());


            Boolean msgStatus = false;        
            Map<String,String> info = new Map<String,String>();
            while(parser.nextToken() != null) {
                if ((parser.getCurrentToken() == JSONToken.FIELD_NAME)){
                    String field = parser.getText();
                    parser.nextToken();
                    String value=parser.getText();
                    if(field=='status' && (value=='sent' || value=='queued' || value=='retrying')){
                        msgStatus = true;
                        info.put(field,value);
                    }
                    if(field=='to_number'){
                        info.put(field,value);
                    }else if(field == 'content'){
                        info.put(field,value);
                    }else if(field == 'message_type'){
                        info.put(field,value);
                    }else if(field == 'Sent'){
                        info.put(field,value);
                    }else if(field == 'direction'){
                        info.put(field,value);
                    }
                }
            }

System.debug('Sent Msg Status: '+info.get('status'));
System.debug('info:'+info);*/
            return new MogliSendSMSOutput();
        }
    }


    public static MogliSendSMSOutput sendSMS(MogliSendSMSInput input){
        System.debug('MogliSMSService.sendSMS()');
 

        String handlerClassStr;
        if(MogliSMSSettings.settings.Gateway__c == 'TWILIO'){
            handlerClassStr = 'MogliSMSService.TwilioSendSMSHandler';
        } else if(MogliSMSSettings.settings.Gateway__c == 'TELERIVET'){
            handlerClassStr = 'Mogli_Gateways.TelerivetSendSMSHandler';
        } else if(MogliSMSSettings.settings.Gateway__c == 'TXTWIRE'){
            handlerClassStr = 'Mogli_Gateways.TxtWireSendSMSHandler';                         
        } else if(MogliSMSSettings.settings.Gateway__c == 'CUSTOM'){
            handlerClassStr = MogliSMSSettings.settings.CustomSMSServiceHandler__c;                         
        }                   


        Type handlerClass = Type.forName(handlerClassStr);
        IMogliSMSServiceHandler activeServiceHandler = (IMogliSMSServiceHandler)handlerClass.newInstance();
        MogliSendSMSOutput returnVal = activeServiceHandler.sendSMSMessage(input);

        return returnVal;

    }

    public with sharing class AssociateSMS implements Queueable{
        public void execute(QueueableContext context){
            System.debug('MogliSMSService.AssociateSMS.execute()');
            List<SMS__c> unassociatedSMS = new List<SMS__c>();
            if((Schema.sObjectType.SMS__c.isAccessible()) &&
               (Schema.sObjectType.SMS__c.fields.Phone_Number__c.isAccessible())){//} &&
 //              (Schema.sObjectType.SMS__c.fields.Lead__c.isAccessible()) &&
//               (Schema.sObjectType.SMS__c.fields.Contact__c.isAccessible())){
                unassociatedSMS = [SELECT id, Phone_Number__c, Lead__c, Contact__c
                                    FROM SMS__c
                                    WHERE Lead__c = null and
                                            Contact__c = null
                                            and Status__c != 'Queued' limit 1000];
            } else {
//                unassociatedSMS = null;
            }
 

            System.debug('unassociatedSMS:'+unassociatedSMS);
            Set<String> likeFilters = new Set<String>();
            if(unassociatedSMS!=null){
                for(SMS__c sms : unassociatedSMS){
                    likeFilters.add('%'+sms.Phone_Number__c+'%');
                }                
            }

            System.debug('likeFilters:'+likeFilters);
            List<Contact> contactList = new List<Contact>();
            List<Lead> leadList = new List<Lead>();     
//            if((Schema.sObjectType.Contact.isAccessible()) &&
//               (Schema.sObjectType.Contact.fields.MobilePhone.isAccessible())){
            contactList = [SELECT id, MobilePhone, Mogli_Number__c FROM Contact where Mogli_Number__c like :likeFilters limit 24000];
//            if((Schema.sObjectType.Lead.isAccessible()) &&
//               (Schema.sObjectType.Lead.fields.MobilePhone.isAccessible())){
            leadList = [SELECT id, MobilePhone, Mogli_Number__c from Lead WHERE Mogli_Number__c like: likeFilters limit 25000];

            System.debug(contactList);
            System.debug(leadList);

            Map<String, Contact> contactByNumber = new Map<String, Contact>();
            Map<String, Lead> leadByNumber = new Map<String, Lead>();
            for(Contact cont : contactList){
                if(!contactByNumber.containsKey(cont.Mogli_Number__c)){
                    contactByNumber.put(cont.Mogli_Number__c, cont);
                }
            }
            for(Lead ld : leadList){
                if(!leadByNumber.containsKey(ld.Mogli_Number__c)){
                    leadByNumber.put(ld.Mogli_Number__c, ld);
                }
            }

            List<SMS__c> smsToUpdate = new List<SMS__c>();
            Set<String> anonPhoneNumbers = new Set<String>();
            List<Lead> anonLeads = new List<Lead>();
            for(SMS__c sms : unassociatedSMS){
                System.debug('sms:'+sms);
                if(contactByNumber.containsKey(sms.Phone_Number__c)){
                    sms.Contact__c = contactByNumber.get(sms.Phone_Number__c).id;
                    smsToUpdate.add(sms);
                } else if (leadByNumber.containsKey(sms.Phone_Number__c)){
                    sms.Lead__c = leadByNumber.get(sms.Phone_Number__c).id;
                    smsToUpdate.add(sms);
                } else {
                    anonPhoneNumbers.add(sms.Phone_Number__c);
                }
            }
            if(MogliSMSSettings.settings.Create_Anonymous_Leads__c){
                for(String phone : anonPhoneNumbers){
                    anonLeads.add(new Lead(LastName = 'Anonymous Lead from Mogli',
                                            Company = 'Anonymous',
                                            Mogli_Number__c = phone));
                }                
            }


            if(smsToUpdate.size()>0){
                System.debug('smsToUpdate'+smsToUpdate);
                if(MogliUtil.respectUserSecurityDML()){
                    if(SMS__c.sObjectType.getDescribe().isUpdateable()){
                        Database.update(smsToUpdate,true);            
                    } else {
                        throw new MogliSMSServiceException('MogliSMSService - Insufficient Access to Update SMS__c');
                    }
                } else {
//                    Database.update(smsToUpdate,true);            
                }

            }

            if(anonLeads.size()>0){
                System.debug('anonLeads'+anonLeads);
                if(MogliUtil.respectUserSecurityDML()){
                    if(Lead.sObjectType.getDescribe().isCreateable()){
                        Database.insert(anonLeads,true);            
                    } else {
                        throw new MogliSMSServiceException('MogliSMSService - Insufficient Access to Create Lead');
                    }
                } else {
//                    Database.insert(anonLeads,true);            
                }
            }
        }
    }
    public with sharing class AssociateForms implements Queueable{
        public void execute(QueueableContext context){
            System.debug('MogliSMSService.AssociateForms.execute()');

            List<Form__c> unassociatedForms = new List<Form__c>();
            if((Schema.sObjectType.Form__c.isAccessible()) &&
               (Schema.sObjectType.Form__c.fields.Phone_Number__c.isAccessible())){//} &&
//               (Schema.sObjectType.Form__c.fields.Lead__c.isAccessible()) &&
//               (Schema.sObjectType.Form__c.fields.Contact__c.isAccessible())){
                    unassociatedForms = [SELECT id, Phone_Number__c, Lead__c, Contact__c
                                                  FROM Form__c
                                                  WHERE Lead__c = null and
                                                        Contact__c = null limit 1000];
            }


            System.debug('unassociatedForms:'+unassociatedForms);

            Set<String> likeFilters = new Set<String>();
            if(unassociatedForms!=null){
                 for(Form__c form : unassociatedForms){
                    likeFilters.add('%'+form.Phone_Number__c+'%');
                }               
            }

            System.debug('likeFilters:'+likeFilters);

            List<Contact> contactList = new List<Contact>();
            List<Lead> leadList = new List<Lead>();     
//            if((Schema.sObjectType.Contact.isAccessible()) &&
//               (Schema.sObjectType.Contact.fields.MobilePhone.isAccessible())){
                contactList = [SELECT id, MobilePhone, Mogli_Number__c FROM Contact where Mogli_Number__c like :likeFilters limit 24000];

//            if((Schema.sObjectType.Lead.isAccessible()) &&
//               (Schema.sObjectType.Lead.fields.MobilePhone.isAccessible())){
                leadList = [SELECT id, MobilePhone, Mogli_Number__c from Lead WHERE Mogli_Number__c like: likeFilters limit 25000];



            System.debug(leadList);

            Map<String, Contact> contactByNumber = new Map<String, Contact>();
            Map<String, Lead> leadByNumber = new Map<String, Lead>();
            for(Contact cont : contactList){
                if(!contactByNumber.containsKey(cont.Mogli_Number__c)){
                    contactByNumber.put(cont.Mogli_Number__c, cont);
                }
            }
            for(Lead ld : leadList){
                if(!leadByNumber.containsKey(ld.Mogli_Number__c)){
                    leadByNumber.put(ld.Mogli_Number__c, ld);
                }
            }

            List<Form__c> formsToUpdate = new List<Form__c>();
            for(Form__c form : unassociatedForms){
                if(contactByNumber.containsKey(form.Phone_Number__c)){
                    form.Contact__c = contactByNumber.get(form.Phone_Number__c).id;
                    formsToUpdate.add(form);
                } else if (leadByNumber.containsKey(form.Phone_Number__c)){
                    form.Lead__c = leadByNumber.get(form.Phone_Number__c).id;
                    formsToUpdate.add(form);
                }
            }
            if(formsToUpdate.size()>0){

                if(MogliUtil.respectUserSecurityDML()){
                    if(Form__c.sObjectType.getDescribe().isUpdateable()){
                        Database.update(formsToUpdate,true);            
                    } else {
                        throw new MogliSMSServiceException('MogliSMSService - Insufficient Access to Update Form__c');
                    }
                } else {
                    Database.update(formsToUpdate,true);            
                }
            }
        }
    }
    public with sharing class SendScheduledSMS implements Queueable{
        public void execute(QueueableContext context){
            System.debug('MogliSMSService.SendScheduledSMS.execute()');
            List<SMS__c> scheduledSMS = new List<SMS__c>();
            if((Schema.sObjectType.SMS__c.isAccessible()) &&
               (Schema.sObjectType.SMS__c.fields.Message__c.isAccessible()) &&
               (Schema.sObjectType.SMS__c.fields.Status__c.isAccessible())){
                scheduledSMS = [SELECT id, Message__c, Status__c from SMS__c where Status__c = 'Scheduled' and Scheduled_Delivery__c < :DateTime.Now() limit 50000];
                system.debug('scheduledSMS:'+scheduledSMS);
            } else {
                scheduledSMS = null;
            }

            for (SMS__c sms : scheduledSMS){
                sms.Status__c = 'Sending';
            }
            if(scheduledSMS.size()>0){
                if(MogliUtil.respectUserSecurityDML()){
                    if(SMS__c.sObjectType.getDescribe().isUpdateable()){
                        Database.update(scheduledSMS,true);            
                    } else {
                        throw new MogliSMSServiceException('MogliSMSService - Insufficient Access to Update SMS__c');
                    }
                } else {
                    Database.update(scheduledSMS,true);            
                }

            }


            //Batch them
            BatchDispatch.BatchDispatchContext bc = new BatchDispatch.BatchDispatchContext();
            bc.batchHandler = 'SendSMSBatchHandler';
            BatchDispatch job = new BatchDispatch(bc);
            Database.executeBatch(job, 100);


        }
    }
    public with sharing class RetryDelayedSMS implements Queueable{
        public void execute(QueueableContext context){
            System.debug('MogliSMSService.RetryDelayedSMS.execute()');
            List<SMS__c> delayedSMS = new List<SMS__c>();
            if((Schema.sObjectType.SMS__c.isAccessible()) &&
               (Schema.sObjectType.SMS__c.fields.Message__c.isAccessible()) &&
               (Schema.sObjectType.SMS__c.fields.Status__c.isAccessible())){
                delayedSMS = [SELECT id, Message__c, Status__c from SMS__c where Status__c = 'Queued'
                                                                            and SystemModStamp < :DateTime.Now().addMinutes(-1) limit 50000];
            } else {
                delayedSMS = null;
            }

            for (SMS__c sms : delayedSMS){
                sms.Status__c = 'Retry';
            }
            if(delayedSMS.size()>0){
                if(MogliUtil.respectUserSecurityDML()){
                    if(SMS__c.sObjectType.getDescribe().isUpdateable()){
                        Database.update(delayedSMS,true);            
                    } else {
                        throw new MogliSMSServiceException('MogliSMSService - Insufficient Access to Update SMS__c');
                    }
                } else {
                    Database.update(delayedSMS,true);            
                }

            }
            for (SMS__c sms : delayedSMS){
                sms.Status__c = 'Queued';
            }
            if(delayedSMS.size()>0){
                if(MogliUtil.respectUserSecurityDML()){
                    if(SMS__c.sObjectType.getDescribe().isUpdateable()){
                        Database.update(delayedSMS,true);            
                    } else {
                        throw new MogliSMSServiceException('MogliSMSService - Insufficient Access to Update SMS__c');
                    }
                } else {
                    Database.update(delayedSMS,true);            
                }

            }
        }
    }

    public class MogliSMSServiceException extends Exception{}
}