code/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mogli_Number__c</fullName>
        <description>This is the gateway formatted phone number</description>
        <externalId>true</externalId>
        <inlineHelpText>This is the gateway formatted phone number</inlineHelpText>
        <label>Mogli Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

code/objects/Gateway__c.object
<CustomObject>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <label>Gateway</label>
    <nameField>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/SMS__c.object
<CustomObject>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incoming</fullName>
                </value>
                <value>
                    <fullName>Outgoing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gateway</label>
        <referenceTo>Gateway__c</referenceTo>
        <relationshipLabel>SMS</relationshipLabel>
        <relationshipName>SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS{YY}{MM}{DD}-{0000}</displayFormat>
        <label>SMS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/SMS_Template__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <label>SMS Template</label>
    <nameField>
        <displayFormat>ST{YY}{MM}{DD}-{0000000000}</displayFormat>
        <label>SMS Template #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/classes/TextMessageComponentController_TEST.cls
@isTest
public class TextMessageComponentController_TEST {

	@TestSetup static void setupData(){
        TestUtil.setStandardTestConditions();
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Contact';
        con.Mogli_Number__c ='+7777';
        insert con;

        Gateway__c gat = new Gateway__c();
        gat.Name = 'Default Gateway';
        gat.Inactive__c = false;
        insert gat;

        SMS__c sms = new SMS__c();
        sms.Message__c = 'Test Message';
        sms.Phone_Number__c = '+7777';
        sms.Direction__c = 'Incoming';
        sms.Gateway__c = gat.Id;
        insert sms;


        System.assert(true);
    }


	static testMethod void testGetSMSMessageThread(){
		Contact con = [select Id from Contact where Mogli_Number__c = '+7777' ];
		Test.startTest();
		List<SMS__c> smss = TextMessageComponentController.getSMSMessageThread(con.Id);
		Test.stopTest();
		System.assertEquals(1, smss.size());
	}

	static testMethod void testSendSMSMessage(){
		Contact con = [select Id from Contact where Mogli_Number__c = '+7777' ];
		Test.startTest();
		TextMessageComponentController.sendSMSMessage(con.Id, 'Message', '-Default-');
		Test.stopTest();
		List<SMS__c> smss = [Select Id from SMS__c where Phone_Number__c = '+7777'];
		System.assertEquals(2, smss.size());
	}

	static testMethod void testGetSessionId(){
		Test.startTest();
		String sessionId = TextMessageComponentController.getSessionId();
		Test.stopTest();
	}

	static testMethod void testVerifyMessage(){
		Contact con = [select Id from Contact where Mogli_Number__c = '+7777' ];
		Test.startTest();
		Boolean verified = TextMessageComponentController.verifyMessage(con.Id, '+7777');
		Test.stopTest();
		System.assert(verified);
	}

	static testMethod void testGetOriginationList(){
		Test.startTest();
		List<String> gateways = TextMessageComponentController.getOriginationList();
		Test.stopTest();
		System.assertEquals(3, gateways.size());
	}
    
    static testMethod void testGetSMSTemplates(){
        SMS_Template__c temp = new SMS_Template__c();
        temp.Name__c = 'Template1';
        temp.Text__c = 'Message';
        insert temp;
        Test.startTest();
        List<SMS_Template__c> result = TextMessageComponentController.getSMSTemplates();
        Test.stopTest();
        System.assertEquals(1, result.size());
    }
	
}