code/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mogli_Number__c</fullName>
        <description>This is the gateway formatted phone number</description>
        <externalId>true</externalId>
        <inlineHelpText>This is the gateway formatted phone number</inlineHelpText>
        <label>Mogli Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

code/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offline__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Offline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form</label>
    <nameField>
        <displayFormat>FN{0000000000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/Gateway__c.object
<CustomObject>
    <label>Gateway</label>
    <nameField>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/PossibleAnswer__c.object
<CustomObject>
    <fields>
        <fullName>Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Question</label>
        <referenceTo>QuestionTemplate__c</referenceTo>
        <relationshipLabel>PossibleAnswer</relationshipLabel>
        <relationshipName>From_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PossibleText__c</fullName>
        <label>Possible Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>QuestionTemplate__c</fullName>
        <label>Question Template</label>
        <referenceTo>QuestionTemplate__c</referenceTo>
        <relationshipLabel>Possible Answers</relationshipLabel>
        <relationshipName>Possible_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Possible Answer</label>
    <nameField>
        <displayFormat>PAN{0000000000}</displayFormat>
        <label>Possible Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Possible Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

code/objects/QuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gateway</label>
        <referenceTo>Gateway__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mogli_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will link the Question Response to the original Outbound Mogli message.</description>
        <inlineHelpText>This field will link the Question Response to the original Outbound Mogli message.</inlineHelpText>
        <label>Mogli Question</label>
        <referenceTo>SMS__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mogli_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will link the Question Response to the original Inbound Mogli message.</description>
        <inlineHelpText>This field will link the Question Response to the original Inbound Mogli message.</inlineHelpText>
        <label>Mogli Response</label>
        <referenceTo>SMS__c</referenceTo>
        <relationshipLabel>Question Responses (Mogli Response)</relationshipLabel>
        <relationshipName>Question_Responses1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Template</label>
        <referenceTo>QuestionTemplate__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <description>Copy of the question text that was asked at the time of the question (in case the question template changes)</description>
        <inlineHelpText>Copy of the question text that was asked at the time of the question (in case the question template changes)</inlineHelpText>
        <label>Question Text</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <type>TextArea</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QRN{0000000000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

code/objects/QuestionTemplate__c.object
<CustomObject>
    <fields>
        <fullName>DefaultNextQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Next Question</label>
        <referenceTo>QuestionTemplate__c</referenceTo>
        <relationshipLabel>Question Templates</relationshipLabel>
        <relationshipName>DefaultedFromQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message_Text__c</fullName>
        <label>Message Text</label>
        <type>TextArea</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

code/objects/SMS__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SMS</relationshipLabel>
        <relationshipName>SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incoming</fullName>
                </value>
                <value>
                    <fullName>Outgoing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gateway</label>
        <referenceTo>Gateway__c</referenceTo>
        <relationshipLabel>SMS</relationshipLabel>
        <relationshipName>SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Offline__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Offline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Sending</fullName>
                </value>
                <value>
                    <fullName>Sent Successfully</fullName>
                </value>
                <value>
                    <fullName>Received Successfully</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS{YY}{MM}{DD}-{0000}</displayFormat>
        <label>SMS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/classes/QuestionResponseTriggerHandler.cls
public with sharing class QuestionResponseTriggerHandler implements TriggerDispatch.ITriggerClass{

    /**************************Static Variables**********************************/

    /**************************State Control Variables**********************************/
    public static boolean mainHasRun = false;
    public static boolean inProgressHasRun = false;
    
    /**************************Constructors**********************************************/
    
    /**************************Execution Control - Entry Points**********************************/
    public void MainEntry(TriggerDispatch.TriggerContext tc){
system.debug('***QuestionResponseTriggerHandler.MainEntry');
       
        mainHasRun = true;
            
        if(tc.handler == 'QuestionResponseTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'QuestionResponseTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'QuestionResponseTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        
        //the following lines should theoretically never be called but could be called from a simulated transaction
        else if(tc.handler == 'QuestionResponseTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'QuestionResponseTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'QuestionResponseTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'QuestionResponseTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
            

    }
    public void InProgressEntry(TriggerDispatch.TriggerContext tc){
system.debug('***QuestionResponseTriggerHandler.InProgressEntry');

        inProgressHasRun = true;
    
         //Call Desired Functions - Or Not - Given this is InProgressEntry
        if(tc.handler == 'QuestionResponseTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'QuestionResponseTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'QuestionResponseTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        else if(tc.handler == 'QuestionResponseTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'QuestionResponseTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'QuestionResponseTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'QuestionResponseTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
        
        //This is where to decide whether or not to allow other triggers to fire based upon DML on other handlerects
        else if(tc.handler != 'QuestionResponseTriggerHandler'){
            //Determine what to do with other triggers - either kill them or forward them along
            TriggerDispatch.forwardTrigger(tc, this);               
        }

    }
    
    public void onBeforeInsert(TriggerDispatch.TriggerContext tc){
       //Recast the trigger context variables into the appropriate shandlerect types
        List<QuestionResponse__c> newQuestionResponseList = (List<QuestionResponse__c>)tc.newList;
        //This is where you should call your business logic

    }
    public void onBeforeUpdate(TriggerDispatch.TriggerContext tc){
        //Recast the trigger context variables into the appropriate shandlerect types
        List<QuestionResponse__c> newQuestionResponseList = (List<QuestionResponse__c>)tc.newList;
        List<QuestionResponse__c> oldQuestionResponseList = (List<QuestionResponse__c>)tc.oldList;
        Map<ID, QuestionResponse__c> newQuestionResponseMap = (Map<ID, QuestionResponse__c>)tc.newMap;
        Map<ID, QuestionResponse__c> oldQuestionResponseMap = (Map<ID, QuestionResponse__c>)tc.oldMap;
        //This is where you should call your business logic



        
    }
    public void onBeforeDelete(TriggerDispatch.TriggerContext tc){
       //Recast the trigger context variables into the appropriate shandlerect types
        List<QuestionResponse__c> oldQuestionResponseList = (List<QuestionResponse__c>)tc.oldList;
        Map<ID, QuestionResponse__c> oldQuestionResponseMap = (Map<ID, QuestionResponse__c>)tc.oldMap;
        //This is where you should call your business logic
        
  
    }
    
    /****************************After logic****************************************/
    public void onAfterInsert(TriggerDispatch.TriggerContext tc){
         //Recast the trigger context variables into the appropriate shandlerect types
        List<QuestionResponse__c> newQuestionResponseList = (List<QuestionResponse__c>)tc.newList;
        Map<ID, QuestionResponse__c> newQuestionResponseMap = (Map<ID, QuestionResponse__c>)tc.newMap;
        //This is where you should call your business logic

        }
    public void onAfterUpdate(TriggerDispatch.TriggerContext tc){
system.debug('***QuestionResponseTriggerHandler.onAfterUpdate');

        //Recast the trigger context variables into the appropriate shandlerect types
        List<QuestionResponse__c> newQuestionResponseList = (List<QuestionResponse__c>)tc.newList;
        List<QuestionResponse__c> oldQuestionResponseList = (List<QuestionResponse__c>)tc.oldList;
        Map<ID, QuestionResponse__c> newQuestionResponseMap = (Map<ID, QuestionResponse__c>)tc.newMap;
        Map<ID, QuestionResponse__c> oldQuestionResponseMap = (Map<ID, QuestionResponse__c>)tc.oldMap;
        
        //This is where you should call your business logic
        Set<ID> responseIDsToHandle = new Set<ID>();
        for(QuestionResponse__c qr : newQuestionResponseList){
            if((!String.isEmpty(qr.Response__c)) && (String.isEmpty(oldQuestionResponseMap.get(qr.id).Response__c))){
                responseIDsToHandle.add(qr.id); //only add the ids of records whose response was changed from a blank value
            }
        }
        //handleResponse(newQuestionResponseMap.keySet());
        handleResponse(responseIDsToHandle);
    }
    
    public void onAfterDelete(TriggerDispatch.TriggerContext tc){
        //Recast the trigger context variables into the appropriate shandlerect types
        List<QuestionResponse__c> oldQuestionResponseList = (List<QuestionResponse__c>)tc.oldList;
        Map<ID, QuestionResponse__c> oldQuestionResponseMap = (Map<ID, QuestionResponse__c>)tc.oldMap;
        //This is where you should call your business logic

     }
    public void onAfterUndelete(TriggerDispatch.TriggerContext tc){
        //Recast the trigger context variables into the appropriate shandlerect types
        List<QuestionResponse__c> newQuestionResponseList = (List<QuestionResponse__c>)tc.newList;
        Map<ID, QuestionResponse__c> newQuestionResponseMap = (Map<ID, QuestionResponse__c>)tc.newMap;
        //This is where you should call your business logic

    }


    private static void handleResponse(Set<ID> questionResponseIDs){
system.debug('***QuestionResponseTriggerHandler.handleResponse');

system.debug('***RUNNING REHYDRATION QUERY****');

        SystemContext sc = new SystemContext();

        Map<ID, QuestionResponse__c> newQuestionResponsesByID = new Map<ID, QuestionResponse__c>(sc.queryQuestionResponses(questionResponseIDs));

system.debug('newQuestionResponsesByID:'+newQuestionResponsesByID);
        //Get the possible answers to the QuestionTemplates
        Set<ID> questionTemplateIDs = new Set<ID>();
        for(QuestionResponse__c response : newQuestionResponsesByID.values()){
            questionTemplateIDs.add(response.QuestionTemplate__c);
        }

        Map<ID, PossibleAnswer__c> possibleAnswersByID = new Map<ID, PossibleAnswer__c>(sc.queryPossibleAnswers(questionTemplateIDs));

        //Check to see if the answer received is in the list of possible answers
        Map<String, PossibleAnswer__c> possibleAnswerByText = new Map<String, PossibleAnswer__c>();
        for(PossibleAnswer__c answer : possibleAnswersByID.values()){
            //parse the possible text into unique strings
            List<String> possibleAnswers = answer.PossibleText__c.split(MogliSMSSettings.getAppSettings().PossibleAnswerDelimiter__c);
            for(String s: possibleAnswers){
                possibleAnswerByText.put(s.toUpperCase(), answer);
            }
        }
system.debug('newQuestionResponsesByID:'+newQuestionResponsesByID);
system.debug('possibleAnswerByText:'+possibleAnswerByText);     

        List<SMS__c> nextQuestionsToAsk = new List<SMS__c>();
        for(QuestionResponse__c response : newQuestionResponsesByID.values()){
            if(!String.isEmpty(response.Response__c)){ //make sure the response contains a string
                if(possibleAnswerByText.containsKey((response.Response__c).toUpperCase())){
                    //response was found - handle it accordingly
                    if(!String.isEmpty(possibleAnswerByText.get(response.Response__c.toUpperCase()).Next_Question__c)){ //the answer found has a next question
                        if(!String.isEmpty(possibleAnswerByText.get(response.Response__c.toUpperCase()).Next_Question__r.Message_Text__c)){ //the next question has appropriate text
                            SMS__c newQuestion = new SMS__c();

                            newQuestion.Phone_Number__c = response.Form__r.Phone_Number__c;
                            newQuestion.Message__c = possibleAnswerByText.get(response.Response__c.toUpperCase()).Next_Question__r.Message_Text__c;
                            newQuestion.Direction__c = 'Outgoing';
                            newQuestion.Status__c = 'Queued';
                            newQuestion.Offline__c = response.Form__r.Offline__c;
                            newQuestion.Gateway__c = response.Gateway__c;

                            nextQuestionsToAsk.add(newQuestion);
                        }
                    }

                } else {
                    if(!String.isEmpty(response.QuestionTemplate__c)){ //Response has an associated question template
                        if(!String.isEmpty(response.QuestionTemplate__r.DefaultNextQuestion__c)) {//question template has a default next question
                            if(!String.isEmpty(response.QuestionTemplate__r.DefaultNextQuestion__r.Message_Text__c)){ //default question has appropriate text
                                //response was not found but a default question was found - so ask it
                                SMS__c newQuestion = new SMS__c();

                                newQuestion.Phone_Number__c = response.Form__r.Phone_Number__c;
                                newQuestion.Message__c = response.QuestionTemplate__r.DefaultNextQuestion__r.Message_Text__c;
                                newQuestion.Direction__c = 'Outgoing';
                                newQuestion.Status__c = 'Queued';
                                newQuestion.Offline__c = response.Form__r.Offline__c;
                                newQuestion.Gateway__c = response.Gateway__c;

                                nextQuestionsToAsk.add(newQuestion);
                            }
                        } 
                    }
                }           
            }
        }




system.debug('nextQuestionsToAsk:'+nextQuestionsToAsk);
        if(nextQuestionsToAsk.size()>0){
            if(MogliUtil.respectUserSecurityDML()){
                if(SMS__c.sObjectType.getDescribe().isCreateable()){
                    Database.insert(nextQuestionsToAsk,true);            
                } else {
                    throw new QuestionResponseTriggerHandlerException('QuestionResponseTriggerHandler - Insufficient Access to Insert SMS__c');
                }
            } else {
                Database.insert(nextQuestionsToAsk,true);            
            }
        }
    }

    public without sharing class SystemContext{
        public List<QuestionResponse__c> queryQuestionResponses(Set<ID> questionResponseIDs){
system.debug('QuestionResponseTriggerHandler.SystemContext.queryQuestionResponses()');
            if((Schema.sObjectType.QuestionResponse__c.isAccessible()) &&
               (Schema.sObjectType.QuestionResponse__c.fields.Form__c.isAccessible()) &&
               (Schema.sObjectType.QuestionResponse__c.fields.QuestionTemplate__c.isAccessible()) &&
               (Schema.sObjectType.QuestionResponse__c.fields.Question_Text__c.isAccessible()) &&
                (Schema.sObjectType.QuestionResponse__c.fields.Response__c.isAccessible()) &&
                (Schema.sObjectType.Form__c.isAccessible()) &&
                (Schema.sObjectType.Form__c.fields.Phone_Number__c.isAccessible()) &&
//                (Schema.sObjectType.Form__c.fields.Contact__c.isAccessible()) &&
                (Schema.sObjectType.Form__c.fields.Offline__c.isAccessible()) &&
//                (Schema.sObjectType.Contact.isAccessible()) &&   
//                (Schema.sObjectType.Contact.fields.MobilePhone.isAccessible()) &&
                (Schema.sObjectType.QuestionTemplate__c.isAccessible()) &&   
                (Schema.sObjectType.QuestionTemplate__c.fields.DefaultNextQuestion__c.isAccessible()) &&
                (Schema.sObjectType.QuestionTemplate__c.fields.Message_Text__c.isAccessible())){
                    return [SELECT id, Form__c, Form__r.Phone_Number__c, Form__r.Contact__r.MobilePhone, Form__r.Contact__r.Mogli_Number__c, Form__r.Contact__c,
                            Form__r.Offline__c,
                            QuestionTemplate__c, QuestionTemplate__r.DefaultNextQuestion__c,
                            QuestionTemplate__r.DefaultNextQuestion__r.Message_Text__c,
                            Question_Text__c, Response__c, Mogli_Question__c, Mogli_Response__c, Gateway__c 
                            FROM QuestionResponse__c where ID = :questionResponseIDs
                            LIMIT 50000];
            } else {
system.debug('fields not accessible');
                return null;
            }


        }

        public List<PossibleAnswer__c> queryPossibleAnswers(Set<ID> questionTemplateIDs){
system.debug('QuestionResponseTriggerHandler.SystemContext.queryPossibleAnswers()'); 
            if((Schema.sObjectType.PossibleAnswer__c.isAccessible()) &&
               (Schema.sObjectType.PossibleAnswer__c.fields.Next_Question__c.isAccessible()) &&
               (Schema.sObjectType.PossibleAnswer__c.fields.PossibleText__c.isAccessible()) &&
               (Schema.sObjectType.PossibleAnswer__c.fields.QuestionTemplate__c.isAccessible()) &&
                (Schema.sObjectType.QuestionTemplate__c.isAccessible()) &&
                (Schema.sObjectType.QuestionTemplate__c.fields.Message_Text__c.isAccessible())){
                return [SELECT ID, Next_Question__c, PossibleText__c, QuestionTemplate__c,
                        Next_Question__r.Message_Text__c
                        FROM PossibleAnswer__c
                        WHERE QuestionTemplate__c = :questionTemplateIDs
                        LIMIT 50000];            
            } else {
                return null;
            }

        }
    }


    public class QuestionResponseTriggerHandlerException extends Exception {}
 }