code/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mogli_Number__c</fullName>
        <description>This is the gateway formatted phone number</description>
        <externalId>true</externalId>
        <inlineHelpText>This is the gateway formatted phone number</inlineHelpText>
        <label>Mogli Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

code/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FormTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Form Template</label>
        <referenceTo>FormTemplate__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form</label>
    <nameField>
        <displayFormat>FN{0000000000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/FormTemplate__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form Template</label>
    <nameField>
        <label>Form Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/PossibleAnswer__c.object
<CustomObject>
    <fields>
        <fullName>Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Question</label>
        <referenceTo>QuestionTemplate__c</referenceTo>
        <relationshipLabel>PossibleAnswer</relationshipLabel>
        <relationshipName>From_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PossibleText__c</fullName>
        <label>Possible Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>QuestionTemplate__c</fullName>
        <label>Question Template</label>
        <referenceTo>QuestionTemplate__c</referenceTo>
        <relationshipLabel>Possible Answers</relationshipLabel>
        <relationshipName>Possible_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Possible Answer</label>
    <nameField>
        <displayFormat>PAN{0000000000}</displayFormat>
        <label>Possible Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Possible Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

code/objects/QuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QuestionTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Template</label>
        <referenceTo>QuestionTemplate__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <description>Copy of the question text that was asked at the time of the question (in case the question template changes)</description>
        <inlineHelpText>Copy of the question text that was asked at the time of the question (in case the question template changes)</inlineHelpText>
        <label>Question Text</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <type>TextArea</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QRN{0000000000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

code/objects/QuestionTemplate__c.object
<CustomObject>
    <fields>
        <fullName>DefaultNextQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Next Question</label>
        <referenceTo>QuestionTemplate__c</referenceTo>
        <relationshipLabel>Question Templates</relationshipLabel>
        <relationshipName>DefaultedFromQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FirstQuestion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Question</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FormComplete__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Form Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FormTemplate__c</fullName>
        <label>Form Template</label>
        <referenceTo>FormTemplate__c</referenceTo>
        <relationshipLabel>Question Templates</relationshipLabel>
        <relationshipName>Question_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Message_Text__c</fullName>
        <label>Message Text</label>
        <type>TextArea</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

code/objects/SMS__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SMS</relationshipLabel>
        <relationshipName>SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incoming</fullName>
                </value>
                <value>
                    <fullName>Outgoing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Sending</fullName>
                </value>
                <value>
                    <fullName>Sent Successfully</fullName>
                </value>
                <value>
                    <fullName>Received Successfully</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS{YY}{MM}{DD}-{0000}</displayFormat>
        <label>SMS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/SMS_Template__c.object
<CustomObject>
    <fields>
        <fullName>FormTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The form that will be initiated upon sending this template</description>
        <inlineHelpText>The form that will be initiated upon sending this template</inlineHelpText>
        <label>Form Template</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Active Forms maybe selected</errorMessage>
            <filterItems>
                <field>FormTemplate__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <infoMessage>Only Active Forms maybe selected</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FormTemplate__c</referenceTo>
        <relationshipLabel>SMS Templates</relationshipLabel>
        <relationshipName>SMS_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <label>SMS Template</label>
    <nameField>
        <displayFormat>ST{YY}{MM}{DD}-{0000000000}</displayFormat>
        <label>SMS Template #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/classes/QuestionResponseTriggerHandler_TEST.cls
@isTest private class QuestionResponseTriggerHandler_TEST {

    private static Map<ID, Contact> initialContactsByID;
    private static Map<ID, Form__c> initialFormsByID;
    private static Map<ID, FormTemplate__c> initialFormTemplatesByID;
    private static Map<ID, PossibleAnswer__c> initialPossibleAnswersByID;
    private static Map<ID, QuestionTemplate__c> initialQuestionTemplatesByID;
    private static Map<ID, SMS_Template__c> initialSMSTemplatesByID;
    private static Map<ID, SMS__c> initialOutgoingSMSByID;

    @TestSetup static void setupData(){
system.debug('QuestionResponseTriggerHandler_TEST.setupData()');
        TestUtil.setStandardTestConditions();
        system.assert(true);
        initialContactsByID = TestUtil.createAndInsertContacts(TestUtil.TEST_THROTTLE);


        initialFormTemplatesByID = TestUtil.createAndInsertFormTemplates(TestUtil.TEST_THROTTLE);
        initialQuestionTemplatesByID = TestUtil.createAndInsertQuestionTemplates(TestUtil.TEST_THROTTLE, initialFormTemplatesByID.values());

        //Create a default question for each form and make it the default question for each associated questionTemplate
        List<QuestionTemplate__c> questionTemplatesToCreate = new List<QuestionTemplate__c>();
        for(FormTemplate__c formT : initialFormTemplatesByID.values()){
            QuestionTemplate__c defaultQ = new QuestionTemplate__c();
            defaultQ.Message_Text__c = 'Default Response';
            defaultQ.FormTemplate__c = formT.id;
            questionTemplatesToCreate.add(defaultQ);
        }
        insert questionTemplatesToCreate;
        Map<ID, QuestionTemplate__c> defaultQuestionsByID = new Map<ID, QuestionTemplate__c>([SELECT id, FormTemplate__c, Message_Text__c, DefaultNextQuestion__c from QuestionTemplate__c WHERE Message_Text__c = 'Default Response']);
        system.assertEquals(defaultQuestionsByID.size(), TestUtil.TEST_THROTTLE, 'Should be one default question per form template');
        //sort by form template id
        Map<ID, List<QuestionTemplate__c>> defaultQuestionsByFormTemplateID = new Map<ID, List<QuestionTemplate__c>>();
        for(QuestionTemplate__c questionT : defaultQuestionsByID.values()){
            if(!defaultQuestionsByFormTemplateID.containsKey(questionT.FormTemplate__c)){
                defaultQuestionsByFormTemplateID.put(questionT.FormTemplate__c, new List<QuestionTemplate__c>());
            }
            defaultQuestionsByFormTemplateID.get(questionT.FormTemplate__c).add(questionT);
        }
        for(QuestionTemplate__c questionT : initialQuestionTemplatesByID.values()){
            questionT.DefaultNextQuestion__c = defaultQuestionsByFormTemplateID.get(questionT.FormTemplate__c)[0].id;
        }

        update initialQuestionTemplatesByID.values(); //update the initial question to now have the default next question


        initialPossibleAnswersByID = TestUtil.createAndInsertPossibleAnswers(TestUtil.TEST_THROTTLE, initialQuestionTemplatesByID.values());

        initialFormTemplatesByID = TestUtil.updateFormTemplatesToActive(initialFormTemplatesByID.values());
        initialSMSTemplatesByID = TestUtil.createandInsertSMSTemplates(TestUtil.TEST_THROTTLE, initialFormTemplatesByID.values());
system.debug('initialSmsTemplatesByID:'+initialSmsTemplatesByID);
        //ask the first question for each active form
        List<SMS__c> outgoingSMSs = new List<SMS__c>();
        for(Integer i = 0; i< TestUtil.TEST_THROTTLE; i++){

            SMS__c sms = new SMS__c();
            sms.Contact__c = initialContactsByID.values()[i].id;
            sms.Direction__c = 'Outgoing';
            sms.Message__c = initialSmsTemplatesByID.values()[i].Text__c;
            sms.Status__c = 'Queued';
//            sms.Phone_Number__c = initialContactsByID.values()[i].MobilePhone;
            sms.Phone_Number__c = initialContactsByID.values()[i].Mogli_Number__c;
            outgoingSMSs.add(sms);
        }
        insert outgoingSMSs;
system.debug('outgoingSMSs'+outgoingSMSs);
        initialOutgoingSMSByID = new Map<ID, SMS__c>([SELECT id, Contact__c, Direction__c, Message__c, Status__c, Phone_Number__c
                                                                FROM SMS__c]);
system.debug('initialOutgoingSMSByID:'+initialOutgoingSMSByID);
    }

    @isTest static void validateBadResponseTriggersDefaultQuestion() {
system.debug('QuestionResponseTriggerHandler_TEST.validateBadResponseTriggersDefaultQuestion()');
        initialContactsByID = new Map<ID, Contact>([SELECT id, LastName, MobilePhone, Mogli_Number__c FROM Contact]);
        initialFormsByID = new Map<ID, Form__c>([SELECT id, FormTemplate__c, Status__c, Contact__c FROM Form__c]);
        initialFormTemplatesByID = new Map<ID, FormTemplate__c>([SELECT id, Status__c FROM FormTemplate__c]);
        initialPossibleAnswersByID = new Map<ID, PossibleAnswer__c>([SELECT id, Next_Question__c, PossibleText__c, QuestionTemplate__c FROM PossibleAnswer__c]);
        initialQuestionTemplatesByID = new Map<ID, QuestionTemplate__c>([SELECT id, DefaultNextQuestion__c, FirstQuestion__c, FormTemplate__c, FormComplete__c, Message_Text__c FROM QuestionTemplate__c]);
        initialSMSTemplatesByID = new Map<ID, SMS_Template__c>([SELECT id, FormTemplate__c, Text__c, Name__c FROM SMS_Template__c]);
        initialOutgoingSMSByID = new Map<ID, SMS__c>([SELECT id, Contact__c, Direction__c, Message__c, Status__c, Phone_Number__c
                                                                FROM SMS__c]);




        system.assertEquals(initialContactsByID.size(), TestUtil.TEST_THROTTLE, 'Wrong number contacts');
        system.assertEquals(initialFormsByID.size(), TestUtil.TEST_THROTTLE, 'Wrong number forms');
        system.assertEquals(initialFormTemplatesByID.size(), TestUtil.TEST_THROTTLE, 'Wrong number form templates');
        system.assertEquals(initialQuestionTemplatesByID.size(), TestUtil.TEST_THROTTLE * (TestUtil.TEST_THROTTLE + 1), 'Wrong number of question templates');
        system.assertEquals(initialPossibleAnswersByID.size(), TestUtil.TEST_THROTTLE * TestUtil.TEST_THROTTLE * TestUtil.TEST_THROTTLE, 'Wrong number of possible answers');
        system.assertEquals(initialSMSTemplatesByID.size(), TestUtil.TEST_THROTTLE, 'Wrong number of SMS templates');       
        system.assertEquals(initialOutgoingSMSByID.size(), TestUtil.TEST_THROTTLE, 'Wrong number of outgoing SMS');     


        Map<ID, QuestionResponse__c> initialQuestionResponsesByID = new Map<ID, QuestionResponse__c>([SELECT id, Form__c, QuestionTemplate__c, Question_Text__c, Response__c FROM QuestionResponse__c]);


        for(QuestionResponse__c response : initialQuestionResponsesByID.values()){
            response.Response__c = 'bad response';
        }
        Test.startTest();
        update initialQuestionResponsesByID.values();
        Test.stopTest();

        //Validate that the default question from the Question_Template was asked
        Map<ID, SMS__c> smsQueueByID = new Map<ID, SMS__c>([SELECT id, Contact__c, Direction__c, 
            Message__c, Status__c, PHone_Number__c FROM SMS__c where id != :initialOutgoingSMSByID.keyset()]); //dont include the original smss
system.debug('smsQueueByID:'+smsQueueByID);
        system.assertEquals(smsQueueByID.size(), TestUtil.TEST_THROTTLE, 'Should be one new default question per contact');

        
        for(SMS__c smsQueue : smsQueueByID.values()){

//Removing link to contact to test for b4l
//            system.assert(initialContactsByID.containsKey(smsQueue.Contact__c), 'Each sms should be associated to a contact');
            system.assertEquals(smsQueue.Message__c, 'Default Response', 'Wrong message');
        }

    }
    @isTest static void validateGoodResponseTriggersNextQuestion() {
        system.assert(true);
    }
    @isTest static void validateUpdatingResponseDoesNotFireNextQuestion(){
        system.assert(true);
    }
}