code/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mogli_Number__c</fullName>
        <description>This is the gateway formatted phone number</description>
        <externalId>true</externalId>
        <inlineHelpText>This is the gateway formatted phone number</inlineHelpText>
        <label>Mogli Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

code/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offline__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Offline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form</label>
    <nameField>
        <displayFormat>FN{0000000000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/QuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QuestionTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Template</label>
        <referenceTo>QuestionTemplate__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <description>Copy of the question text that was asked at the time of the question (in case the question template changes)</description>
        <inlineHelpText>Copy of the question text that was asked at the time of the question (in case the question template changes)</inlineHelpText>
        <label>Question Text</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <type>TextArea</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QRN{0000000000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

code/objects/QuestionTemplate__c.object
<CustomObject>
    <fields>
        <fullName>FormComplete__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Form Complete</label>
        <type>Checkbox</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

code/objects/SMS__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SMS</relationshipLabel>
        <relationshipName>SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incoming</fullName>
                </value>
                <value>
                    <fullName>Outgoing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Offline__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Offline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Sending</fullName>
                </value>
                <value>
                    <fullName>Sent Successfully</fullName>
                </value>
                <value>
                    <fullName>Received Successfully</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS{YY}{MM}{DD}-{0000}</displayFormat>
        <label>SMS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/SMS_Template__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <label>SMS Template</label>
    <nameField>
        <displayFormat>ST{YY}{MM}{DD}-{0000000000}</displayFormat>
        <label>SMS Template #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/classes/InPersonFormExt.cls
public with sharing class InPersonFormExt {

	private final sObject mysObject;

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public InPersonFormExt(ApexPages.StandardController stdController) {
        this.mysObject = (sObject)stdController.getRecord();

        responseSMS = new SMS__c();
        formSurveysToChoose = new List<SelectOption>();
        contactForSurvey = new Contact();

        if((Schema.sObjectType.SMS_Template__c.isAccessible()) &&
           (Schema.sObjectType.SMS_Template__c.fields.Name__c.isAccessible())&&
           (Schema.sObjectType.SMS_Template__c.fields.Text__c.isAccessible())){
            List<SMS_Template__c> templates = new List<SMS_Template__c>([Select id, Name__c, Text__c from SMS_Template__c limit 10000]);
            for(SMS_Template__c temp : templates){
                formSurveysToChoose.add(new SelectOption(temp.Text__c,temp.Text__c));
            } 
        } else {
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'The User does not have the correct access on SMS_Template__c'));           
        }
        
                                                                   
        renderSetup = true;
        renderOutputText = false;
        surveyOver = false;
        renderRespondButton = false;
        renderRestartButton = false;
    }

    public String getRecordName() {
        return 'Hello ' + (String)mysObject.get('name') + ' (' + (Id)mysObject.get('Id') + ')';
    }

    private SMS__c initialSMS = new SMS__c();
 
    public SMS__c responseSMS {get;set;}
    public Contact contactForSurvey {get;set;}
    public List<SelectOption> formSurveysToChoose {get;set;}
    public String selectedSurvey {get;set;}
    
    public Boolean renderSetup {get;set;}
    public Boolean renderOutputText {get;set;}
    public Boolean renderCompleteSection {get;set;}
    public Boolean renderRespondButton {get;set;}
    public Boolean renderRestartButton {get;set;}
    
    public Boolean surveyOver {get;set;}
    
    public String outputText {
        get{
            QuestionResponse__c lastQuestion = new QuestionResponse__c();
            try{
                if((Schema.sObjectType.QuestionResponse__c.isAccessible()) &&
                   (Schema.sObjectType.QuestionResponse__c.fields.Form__c.isAccessible())&&
                   (Schema.sObjectType.QuestionResponse__c.fields.Question_Text__c.isAccessible())&&
                   (Schema.sObjectType.QuestionResponse__c.fields.Response__c.isAccessible())&&
                   (Schema.sObjectType.Form__c.isAccessible())&&
                   (Schema.sObjectType.Form__c.fields.Contact__c.isAccessible())&&
                   (Schema.sObjectType.Form__c.fields.Phone_Number__c.isAccessible())&&
                   (Schema.sObjectType.Form__c.fields.Offline__c.isAccessible())&&
                   (Schema.sObjectType.QuestionTemplate__c.isAccessible())&&
                   (Schema.sObjectType.QuestionTemplate__c.fields.FormComplete__c.isAccessible())){
                        lastQuestion = [SELECT id, Form__c, Question_Text__c, Response__c,
                                        Form__r.Contact__c, Form__r.Phone_Number__c, Form__r.Offline__c,
                                        QuestionTemplate__r.FormComplete__c
                                        FROM QuestionResponse__c
                                        WHERE Form__r.Offline__c = true AND
                                        Form__r.Contact__c = :contactForSurvey.ReportsToId AND
                                        Form__r.Status__c = 'Active' AND
                                        Response__c = ''
                                        LIMIT 50000];
                } else {
                     ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'The User does not have the correct access on QuestionResponse__c, Form__c, or QuestionTemplate__c'));           
                }



                if(lastQuestion.QuestionTemplate__r.FormComplete__c){
                    renderOutputText = false;
                    surveyOver = true;
                    renderCompleteSection = true;
                    renderRespondButton = false;
                }
                return lastQuestion.Question_Text__c;                
            } catch (Exception e){
                surveyOver = true;
                renderOutputText = false;
                renderCompleteSection = true;
                renderRespondButton = false;
                return null;
            }

        }
        set;
    }

    public PageReference start(){
system.debug(selectedSurvey);
system.debug(contactForSurvey);
        initialSMS.Message__c = selectedSurvey;
        initialSMS.Status__c = 'Queued';
        initialSMS.Offline__c = true;
        initialSMS.Direction__c = 'Outgoing';

        Contact cont = new Contact();
        if((Schema.sObjectType.Contact.isAccessible()) &&
           (Schema.sObjectType.Contact.fields.MobilePhone.isAccessible())){
            cont = [Select id, MobilePhone, Mogli_Number__c from Contact where id = :contactForSurvey.ReportsToId limit 1];

        } else {
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'The User does not have the correct access on Contact'));           
        }


 //       initialSMS.Phone_Number__c = cont.MobilePhone;
        initialSMS.Phone_Number__c = cont.Mogli_Number__c;
        initialSMS.Contact__c = cont.id;
        
        if(MogliUtil.respectUserSecurityDML()){
            if((SMS__C.sObjectType.getDescribe().isCreateable()) &&
               (Schema.sObjectType.SMS__c.fields.Status__c.isAccessible()) &&
               (Schema.sObjectType.SMS__c.fields.Phone_Number__c.isAccessible())&&
               (Schema.sObjectType.SMS__c.fields.Offline__c.isAccessible()) &&
               (Schema.sObjectType.SMS__c.fields.Message__c.isAccessible()) &&
               (Schema.sObjectType.SMS__c.fields.Direction__c.isAccessible())){
                Database.insert(initialSMS,true);            
            } else {
                throw new InPersonFormExtException('InPersonFormExt - Insufficient Access to Insert SMS__c');
            }
        } else {
 //           Database.insert(initialSMS,true); 
        }        


        renderSetup = false;
        renderOutputText = true;
        renderRespondButton = true;
        renderRestartButton = true;
        return null;
    }

    public PageReference respond(){
        responseSMS.Status__c = 'Received Successfully';
        responseSMS.Offline__c = true;
        responseSMS.Direction__c = 'Incoming';
        responseSMS.Phone_Number__c = initialSMS.Phone_Number__c;
        responseSMS.Contact__c = initialSMS.Contact__c;


        if(MogliUtil.respectUserSecurityDML()){
            if((SMS__C.sObjectType.getDescribe().isCreateable()) &&
               (Schema.sObjectType.SMS__c.fields.Status__c.isAccessible()) &&
               (Schema.sObjectType.SMS__c.fields.Phone_Number__c.isAccessible())&&
               (Schema.sObjectType.SMS__c.fields.Offline__c.isAccessible()) &&
               (Schema.sObjectType.SMS__c.fields.Message__c.isAccessible()) &&
               (Schema.sObjectType.SMS__c.fields.Direction__c.isAccessible())){
                Database.insert(responseSMS,true);            
            } else {
                throw new InPersonFormExtException('InPersonFormExt - Insufficient Access to Insert SMS__c');
            }
        } else {
//            Database.insert(responseSMS,true); 
        }    

        
        responseSMS = new SMS__c();
 /*       
        MogliSMSService.AssociateSMS job = new MogliSMSService.AssociateSMS();
        System.enqueueJob(job);
        MogliSMSService.AssociateForms job2 = new MogliSMSService.AssociateForms();
        System.enqueueJob(job2);
 */       
        return null;
    }
    public PageReference restart(){
        initialSMS = new SMS__c();
        initialSMS.Message__c = selectedSurvey;
        initialSMS.Status__c = 'Queued';
        initialSMS.Offline__c = true;
        initialSMS.Direction__c = 'Outgoing';

 
        Contact cont = new Contact();
        if((Schema.sObjectType.Contact.isAccessible()) &&
           (Schema.sObjectType.Contact.fields.MobilePhone.isAccessible())){
            cont = [Select id, MobilePhone, Mogli_Number__c from Contact where id = :contactForSurvey.ReportsToId limit 1];

        } else {
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'The User does not have the correct access on Contact'));           
        }


 //       initialSMS.Phone_Number__c = cont.MobilePhone;
        initialSMS.Phone_Number__c = cont.Mogli_Number__c;
        initialSMS.Contact__c = cont.id;


        if(MogliUtil.respectUserSecurityDML()){
            if((SMS__C.sObjectType.getDescribe().isCreateable()) &&
               (Schema.sObjectType.SMS__c.fields.Status__c.isAccessible()) &&
               (Schema.sObjectType.SMS__c.fields.Phone_Number__c.isAccessible())&&
               (Schema.sObjectType.SMS__c.fields.Offline__c.isAccessible()) &&
               (Schema.sObjectType.SMS__c.fields.Message__c.isAccessible()) &&
               (Schema.sObjectType.SMS__c.fields.Direction__c.isAccessible())){
                Database.insert(initialSMS,true);            
            } else {
                throw new InPersonFormExtException('InPersonFormExt - Insufficient Access to Insert SMS__c');
            }
        } else {
//            Database.insert(initialSMS,true); 
        }  
        
        renderSetup = false;
        renderOutputText = true;
        renderCompleteSection = false;
        return null;
    }
    public PageReference newSurvey(){
        initialSMS = new SMS__c();
        renderSetup = true;
        renderOutputText = false;
        renderCompleteSection = false;
		return ApexPages.currentPage();
    }

    public class InPersonFormExtException extends Exception {}
}