code/objects/FormTemplate__c.object
<CustomObject>
    <label>Form Template</label>
    <nameField>
        <label>Form Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/QuestionTemplate__c.object
<CustomObject>
    <fields>
        <fullName>FirstQuestion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Question</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FormTemplate__c</fullName>
        <label>Form Template</label>
        <referenceTo>FormTemplate__c</referenceTo>
        <relationshipLabel>Question Templates</relationshipLabel>
        <relationshipName>Question_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Message_Text__c</fullName>
        <label>Message Text</label>
        <type>TextArea</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

code/objects/SMS_Template__c.object
<CustomObject>
    <fields>
        <fullName>FormTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The form that will be initiated upon sending this template</description>
        <inlineHelpText>The form that will be initiated upon sending this template</inlineHelpText>
        <label>Form Template</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Active Forms maybe selected</errorMessage>
            <filterItems>
                <field>FormTemplate__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <infoMessage>Only Active Forms maybe selected</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FormTemplate__c</referenceTo>
        <relationshipLabel>SMS Templates</relationshipLabel>
        <relationshipName>SMS_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <label>SMS Template</label>
    <nameField>
        <displayFormat>ST{YY}{MM}{DD}-{0000000000}</displayFormat>
        <label>SMS Template #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/classes/SMSTemplateTriggerHandler.cls
public with sharing class SMSTemplateTriggerHandler implements TriggerDispatch.ITriggerClass{

    /**************************Static Variables**********************************/

    /**************************State Control Variables**********************************/
    public static boolean mainHasRun = false;
    public static boolean inProgressHasRun = false;
    
    /**************************Constructors**********************************************/
    
    /**************************Execution Control - Entry Points**********************************/
    public void MainEntry(TriggerDispatch.TriggerContext tc){
system.debug('***SMSTemplateTriggerHandler.MainEntry');
       
        mainHasRun = true;
            
        if(tc.handler == 'SMSTemplateTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'SMSTemplateTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'SMSTemplateTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        
        //the following lines should theoretically never be called but could be called from a simulated transaction
        else if(tc.handler == 'SMSTemplateTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'SMSTemplateTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'SMSTemplateTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'SMSTemplateTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
            

    }
    public void InProgressEntry(TriggerDispatch.TriggerContext tc){
system.debug('***SMSTemplateTriggerHandler.InProgressEntry');

        inProgressHasRun = true;
    
         //Call Desired Functions - Or Not - Given this is InProgressEntry
        if(tc.handler == 'SMSTemplateTriggerHandler' && tc.isBefore && tc.isInsert) onBeforeInsert(tc);
        else if(tc.handler == 'SMSTemplateTriggerHandler' && tc.isBefore && tc.isUpdate) onBeforeUpdate(tc);
        else if(tc.handler == 'SMSTemplateTriggerHandler' && tc.isBefore && tc.isDelete) onBeforeDelete(tc);
        else if(tc.handler == 'SMSTemplateTriggerHandler' && tc.isAfter && tc.isInsert) onAfterInsert(tc);
        else if(tc.handler == 'SMSTemplateTriggerHandler' && tc.isAfter && tc.isUpdate) onAfterUpdate(tc);
        else if(tc.handler == 'SMSTemplateTriggerHandler' && tc.isAfter && tc.isDelete) onAfterDelete(tc);
        else if(tc.handler == 'SMSTemplateTriggerHandler' && tc.isAfter && tc.isUndelete) onAfterUndelete(tc);
        
        //This is where to decide whether or not to allow other triggers to fire based upon DML on other handlerects
        else if(tc.handler != 'SMSTemplateTriggerHandler'){
            //Determine what to do with other triggers - either kill them or forward them along
            TriggerDispatch.forwardTrigger(tc, this);               
        }

    }
    
    public void onBeforeInsert(TriggerDispatch.TriggerContext tc){
system.debug('***SMSTemplateTriggerHandler.onBeforeInsert');

       //Recast the trigger context variables into the appropriate shandlerect types
        List<SMS_Template__c> newSMSTemplateList = (List<SMS_Template__c>)tc.newList;
        //This is where you should call your business logic

        copyFirstQuestion(newSMSTemplateList);
    }
    public void onBeforeUpdate(TriggerDispatch.TriggerContext tc){
system.debug('***SMSTemplateTriggerHandler.onBeforeUpdate');

        //Recast the trigger context variables into the appropriate shandlerect types
        List<SMS_Template__c> newSMSTemplateList = (List<SMS_Template__c>)tc.newList;
        List<SMS_Template__c> oldSMSTemplateList = (List<SMS_Template__c>)tc.oldList;
        Map<ID, SMS_Template__c> newSMSTemplateMap = (Map<ID, SMS_Template__c>)tc.newMap;
        Map<ID, SMS_Template__c> oldSMSTemplateMap = (Map<ID, SMS_Template__c>)tc.oldMap;
        //This is where you should call your business logic

        copyFirstQuestion(newSMSTemplateList);
        
    }
    public void onBeforeDelete(TriggerDispatch.TriggerContext tc){
       //Recast the trigger context variables into the appropriate shandlerect types
        List<SMS_Template__c> oldSMSTemplateList = (List<SMS_Template__c>)tc.oldList;
        Map<ID, SMS_Template__c> oldSMSTemplateMap = (Map<ID, SMS_Template__c>)tc.oldMap;
        //This is where you should call your business logic
        
  
    }
    
    /****************************After logic****************************************/
    public void onAfterInsert(TriggerDispatch.TriggerContext tc){
         //Recast the trigger context variables into the appropriate shandlerect types
        List<SMS_Template__c> newSMSTemplateList = (List<SMS_Template__c>)tc.newList;
        Map<ID, SMS_Template__c> newSMSTemplateMap = (Map<ID, SMS_Template__c>)tc.newMap;
        //This is where you should call your business logic

        }
    public void onAfterUpdate(TriggerDispatch.TriggerContext tc){
        //Recast the trigger context variables into the appropriate shandlerect types
        List<SMS_Template__c> newSMSTemplateList = (List<SMS_Template__c>)tc.newList;
        List<SMS_Template__c> oldSMSTemplateList = (List<SMS_Template__c>)tc.oldList;
        Map<ID, SMS_Template__c> newSMSTemplateMap = (Map<ID, SMS_Template__c>)tc.newMap;
        Map<ID, SMS_Template__c> oldSMSTemplateMap = (Map<ID, SMS_Template__c>)tc.oldMap;
        //This is where you should call your business logic

    }
    
    public void onAfterDelete(TriggerDispatch.TriggerContext tc){
        //Recast the trigger context variables into the appropriate shandlerect types
        List<SMS_Template__c> oldSMSTemplateList = (List<SMS_Template__c>)tc.oldList;
        Map<ID, SMS_Template__c> oldSMSTemplateMap = (Map<ID, SMS_Template__c>)tc.oldMap;
        //This is where you should call your business logic

     }
    public void onAfterUndelete(TriggerDispatch.TriggerContext tc){
        //Recast the trigger context variables into the appropriate shandlerect types
        List<SMS_Template__c> newSMSTemplateList = (List<SMS_Template__c>)tc.newList;
        Map<ID, SMS_Template__c> newSMSTemplateMap = (Map<ID, SMS_Template__c>)tc.newMap;
        //This is where you should call your business logic
        
    }
    
    private void copyFirstQuestion(List<SMS_Template__c> newSMSTemplateList){
system.debug('***SMSTemplateTriggerHandler.copyFirstQuestion');

        //determine which template need to have the first questions copied over
        Set<ID> formTemplateIDs = new Set<ID>();
        for(SMS_Template__c smsTemplate : newSMSTemplateList){
            if(!String.isEmpty(smsTemplate.FormTemplate__c)){
                formTemplateIDs.add(smsTemplate.FormTemplate__c);
            }
        }
        SystemContext sc = new SystemContext();
        Map<ID, QuestionTemplate__c> firstQuestions = new Map<ID, QuestionTemplate__c>(sc.queryFirstQuestions(formTemplateIDs));

        Map<ID, QuestionTemplate__c> firstQuestionsByFormTemplateID = new Map<ID, QuestionTemplate__c>();
        for(QuestionTemplate__c question : firstQuestions.values()){
            firstQuestionsByFormTemplateID.put(question.FormTemplate__c, question);
        }

        for(SMS_Template__c smsTemplate : newSMSTemplateList){
            if(!String.isEmpty(smsTemplate.FormTemplate__c)){
                smsTemplate.Text__c = firstQuestionsByFormTemplateID.get(smsTemplate.FormTemplate__c).Message_Text__c;
            }
        }
    }


    public without sharing class SystemContext{
        public List<QuestionTemplate__c> queryFirstQuestions(Set<ID> formTemplateIDs){
            if((Schema.sObjectType.QuestionTemplate__c.isAccessible()) &&
               (Schema.sObjectType.QuestionTemplate__c.fields.Message_Text__c.isAccessible())&&
               (Schema.sObjectType.QuestionTemplate__c.fields.FormTemplate__c.isAccessible())&&                
               (Schema.sObjectType.QuestionTemplate__c.fields.FirstQuestion__c.isAccessible())){
                return [SELECT id, Name, Message_Text__c, FormTemplate__c, FirstQuestion__c
                        FROM QuestionTemplate__c where FormTemplate__c = :formTemplateIDs and FirstQuestion__c = true LIMIT 50000];
            } else {
                return null;
            }
 

        }
    }




 }