code/objects/FormTemplate__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form Template</label>
    <nameField>
        <label>Form Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/QuestionTemplate__c.object
<CustomObject>
    <fields>
        <fullName>FirstQuestion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Question</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FormTemplate__c</fullName>
        <label>Form Template</label>
        <referenceTo>FormTemplate__c</referenceTo>
        <relationshipLabel>Question Templates</relationshipLabel>
        <relationshipName>Question_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Message_Text__c</fullName>
        <label>Message Text</label>
        <type>TextArea</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

code/objects/SMS_Template__c.object
<CustomObject>
    <fields>
        <fullName>FormTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The form that will be initiated upon sending this template</description>
        <inlineHelpText>The form that will be initiated upon sending this template</inlineHelpText>
        <label>Form Template</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Active Forms maybe selected</errorMessage>
            <filterItems>
                <field>FormTemplate__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <infoMessage>Only Active Forms maybe selected</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FormTemplate__c</referenceTo>
        <relationshipLabel>SMS Templates</relationshipLabel>
        <relationshipName>SMS_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <label>SMS Template</label>
    <nameField>
        <displayFormat>ST{YY}{MM}{DD}-{0000000000}</displayFormat>
        <label>SMS Template #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/classes/SMSTemplateTriggerHandler_TEST.cls
@isTest private class SMSTemplateTriggerHandler_TEST {
    @TestSetup static void setupData(){
        system.assert(true);
        TestUtil.setStandardTestConditions();

        //Create 10 Forms
        TestUtil.createAndInsertPossibleAnswers(TestUtil.TEST_THROTTLE,
                                                TestUtil.createAndInsertQuestionTemplates(TestUtil.TEST_THROTTLE,
                                                    TestUtil.createAndInsertFormTemplates(TestUtil.TEST_THROTTLE).values()).values());
    }
    @isTest static void validateLinkingToAFormCopiesFirstQuestion() {
        Map<ID, QuestionTemplate__c> questionTemplateByID = new Map<ID, QuestionTemplate__c>([SELECT id, Name, FirstQuestion__c, FormTemplate__c, Message_Text__c
                                                                                         FROM QuestionTemplate__c]);
        Map<ID, FormTemplate__c> formTemplateByID = new Map<ID, FormTemplate__c>([SELECT id, Name, Status__c
                                                                            FROM FormTemplate__c]);

        system.assertEquals(questionTemplateByID.size(), TestUtil.TEST_THROTTLE * TestUtil.TEST_THROTTLE);
        system.assertEquals(formTemplateByID.size(), TestUtil.TEST_THROTTLE);


        for(FormTemplate__c form : formTemplateByID.values()){
            form.Status__c = 'Active';
        }
        update formTemplateByID.values();


        //Create a map where the first question of the form is sorted by the form id
        Map<ID, QuestionTemplate__c> firstQuestionByFormTemplateId = new Map<ID, QuestionTemplate__c>();
        for(QuestionTemplate__c question : questionTemplateByID.values()){
            if(question.FirstQuestion__c == true){
                firstQuestionByFormTemplateId.put(question.FormTemplate__c, question);
            }
        }
        system.assertEquals(firstQuestionByFormTemplateId.size(), TestUtil.TEST_THROTTLE, 'Each Template should have 1 first question');

        List<SMS_Template__c> smsTemplateList = new List<SMS_Template__c>();

        Integer cnt = 0;
        for(FormTemplate__c formTemplate : formTemplateByID.values()){
            smsTemplateList.add(new SMS_Template__c(Name__c = 'Test'+cnt,
                                                                FormTemplate__c = formTemplate.id));
            cnt++;
        
        }

        Test.startTest();
        insert smsTemplateList;
        Test.stopTest();

        //Loop through the templates and make sure they are the same as the Form Templates First Question text
        Map<ID, SMS_Template__c> smsTemplateByIDAfterInsert = new Map<ID, SMS_Template__c>([SELECT id, Name__c, Text__c, FormTemplate__c
                                                                                                        FROM SMS_Template__c]);
        for(SMS_Template__c smsTemplate: smsTemplateByIDAfterInsert.values()){
            //loop through the questions for the template and validate the text of the SMS template is the same as the first question within the Form
            system.assertEquals(smsTemplate.Text__c, firstQuestionByFormTemplateId.get(smsTemplate.FormTemplate__c).Message_Text__c, 'The Text is not the same as the first question for this form');
        }

        //justgethecoverageman!
        update smsTemplateList;
        delete smsTemplateList;
        undelete smsTEmplateList;
    }
}