code/objects/Gateway__c.object
<CustomObject>
    <fields>
        <fullName>CustomSMSServiceHandler__c</fullName>
        <label>Custom SMSServiceHandler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomWebServiceHandler__c</fullName>
        <label>Custom WebServiceHandler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DisplaySequence__c</fullName>
        <label>Display Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PhoneNumber__c</fullName>
        <label>Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TwilioAccountSid__c</fullName>
        <label>Twilio AccountSid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TwilioAuthToken__c</fullName>
        <label>Twilio AuthToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WebHookIdentifier__c</fullName>
        <label>WebHook Identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Gateway</label>
    <nameField>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/classes/GatewayUtil.cls
public with sharing class GatewayUtil {
	public static Map<ID, Gateway__c> gatewayMap = new Map<ID, Gateway__c>([SELECT id,
																				   Name,
																				   RecordTypeID,
																				   DisplaySequence__c,
																				   Inactive__c,
																				   WebhookIdentifier__c,
																				   CustomSMSServiceHandler__c,
																				   CustomWebServiceHandler__c,
																				   PhoneNumber__c,
																				   TwilioAccountSid__c,
																				   TwilioAuthToken__c
																		 	FROM Gateway__c
																		 	WHERE Inactive__c = false
																		 	Order By DisplaySequence__c
																		 	LIMIT 50000]);
	public static Map<String, Gateway__c> gatewayByWebhook = new Map<String, Gateway__c>();
	public static Map<String, Gateway__c> gatewayByName = new Map<String, Gateway__c>();
	static {
		for(Gateway__c gtw : gatewayMap.values()){
			gatewayByWebhook.put(gtw.WebhookIdentifier__c, gtw);
			gatewayByName.put(gtw.Name, gtw);
		}
	}
}