code/objects/Log__c.object
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/objects/SMS__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>SMS</relationshipLabel>
        <relationshipName>SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SMS</relationshipLabel>
        <relationshipName>SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incoming</fullName>
                </value>
                <value>
                    <fullName>Outgoing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Sending</fullName>
                </value>
                <value>
                    <fullName>Sent Successfully</fullName>
                </value>
                <value>
                    <fullName>Received Successfully</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS{YY}{MM}{DD}-{0000}</displayFormat>
        <label>SMS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/classes/OutgoingSMSAsync.cls
global with sharing class OutgoingSMSAsync implements Queueable, Database.AllowsCallouts{
	global OutgoingSMSAsync() {
//		this.smsIDs = new List<String>();
	}
/*	global OutgoingSMSAsync(String smsID){
		this.smsIDs = new List<String>();
		this.smsIDs.add(smsID);
	}*/
	global OutgoingSMSAsync(Set<ID> smsIDs){
		this.smsIDs = smsIDs;
	}
	public Set<ID> smsIDs = new Set<ID>();
	public void execute(QueueableContext context){
//List<Log__c> logs = new List<Log__c>();
System.debug('OutgoingSMSAsync.execute()');
//logs.add(new Log__c(Message__c=('OutgoingSMSAsync.execute()'))); 


		SystemContext sc = new SystemContext();
		List<SMS__c> outgoingMessages = sc.queryMessages(smsIDs);

//logs.add(new Log__c(Message__c=('outgoingMessages'+outgoingMessages))); 
		//Now send them
		for(SMS__c sms : outgoingMessages){
			MogliSMSService.MogliSendSMSInput msg = new MogliSMSService.MogliSendSMSInput(sms.Phone_Number__c, sms.Message__c);
			MogliSMSService.sendSMS(msg);		
		}	
		

		for(SMS__c sms : outgoingMessages){
			//Update the status to 'Sent Successfully'
			sms.Status__c = 'Sent Successfully';
		}
		update outgoingMessages;
//logs.add(new Log__c(Message__c=('outgoingMessages'+outgoingMessages))); 
//insert logs;
	}
	
	public without sharing class SystemContext{
		public List<SMS__c> queryMessages(Set<ID> smsIDS){
			return [SELECT id, Phone_Number__c, Message__c, Status__c,
											Contact__c, Campaign__c, Direction__c 
												FROM SMS__c where id = :smsIDs
												FOR UPDATE];
		}
	}


	global class OutgoingSMSAsyncException extends Exception {}
}