code/objects/SMS__c.object
<CustomObject>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incoming</fullName>
                </value>
                <value>
                    <fullName>Outgoing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS{YY}{MM}{DD}-{0000}</displayFormat>
        <label>SMS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

code/classes/AttachmentTriggerHandler_TEST.cls
@isTest
public with sharing class AttachmentTriggerHandler_TEST {
	@TestSetup
	public static void setupData(){
		TestUtil.setStandardTestConditions();
	}

	@isTest
	public static void validateAttachmentTrigger(){
		SMS__c msg = new SMS__c(Direction__c = 'Inbound');
		insert msg;
		Attachment attachment = new Attachment(Name='An attachment',body=blob.valueof('b'),parentId=msg.Id);
		insert attachment;		
	}

}